# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2023-07"

[[extensions]]
type = "ui_extension"
name = "checkout-fomo"
handle = "checkout-fomo"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
[[extensions.settings.fields]]
key = "fomo_time"
type = "number_integer"
name = "Countdown time in minutes"
description = "Enter the time in minutes to be shown in the countdown."

[[extensions.settings.fields]]
key = "fomo_title"
type = "single_line_text_field"
name = "Title"
description = "Enter the title of the widget example: Products are in high demand! Get yours now before they're gone."

[[extensions.settings.fields]]
key = "fomo_icon"
type = "single_line_text_field"
name = "Icon"
description = "Enter the name of the icon to use all icons can be seen in https://shopify.dev/docs/api/checkout-ui-extensions/2023-07/components/media/icon#icons"

[[extensions.settings.fields]]
key = "hurry_text"
type = "single_line_text_field"
name = "Hurry Text"
description = "In this field you must provide {time} in the text to show the countdown example: Hurry! Your selected items are only reserved for {time}. Complete your order now!"

[[extensions.settings.fields]]
key = "end_text"
type = "single_line_text_field"
name = "Timer ended text"
description = "Enter the text to show after the countdown has ended example: Time's up! Please finish the checkout as the item is still in your cart."